# ---------------------------------------------------------
# GitHub Actions Workflow: Python CI
#
# This workflow:
# 1. Checks out the repository
# 2. Installs Python dependencies
# 3. Runs pre-commit hooks
# 4. Executes tests
#
# Used for validating pull requests and pushes to main.
# ---------------------------------------------------------

name: Pre-commit CI # from pre-commit hooks in local dev. can be different

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit: # can be any label
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # local dev has 3.14 # github servers

      - name: Safety Vulnerability in dependencies
        run: safety check -r requirements.txt --full-report

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files # python package installed in req...
